spring:
  datasource:
    url: jdbc:h2:mem:test;MODE=mysql;
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      encoding: utf-8
  redis:
    host: localhost
    port: 6379
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true